### ISSUE TITLE
Version 0.0.1

### ISSUE THREAD

**Issue by stephenplusplus** [jgeewax/phoenix#8]
@callmehiphop -- you've been leading the FE charge on this one. Can you plop down a list of the things required to have "something" ready for 2 weeks from now (9/25).
- [x] OAuth/API request module (_@stephenplusplus_)
  - Using this library: https://github.com/maximepvrt/angular-google-gapi
    - Currently exposed via `$window.transport`, but waiting on @callmehiphop for a more correct architecture there.
  - [x] Can't get the resource manager API to work from the client side library: https://github.com/google/google-api-javascript-client/issues/202 (_@callmehiphop_)
- [x] Design (_@callmehiphop_)
- [ ] [Plugin `package.json` schema](#12)
- [x] ~~Plugin explorer~~ (future)
- [x] Plugin Loader (_@callmehiphop_)
  - [x] For now, feed it an npm package name
- [ ] Config storage
  - [x] Default to localStorage (_@callmehiphop_)
  - [ ] Support storing in a custom config bucket for our [hosted version](#11)
- [ ] Functional plugin: [`gcloud-static-web-host`](#10)
